@echo off
echo Checking port 8000...
for /f "tokens=5" %%a in ('netstat -aon ^| findstr :8000') do (
    echo Terminating old server process %%a on port 8000...
    taskkill /F /PID %%a >nul 2>&1
)
echo Launching web browser at http://127.0.0.1:8000/ ...
start http://127.0.0.1:8000/
echo Starting Yeast Promoter Modifier server...
python main.py
pause
