@echo off
echo Checking port 8080...
for /f "tokens=5" %%a in ('netstat -aon ^| findstr :8080') do (
    echo Terminating old server process %%a on port 8080...
    taskkill /F /PID %%a >nul 2>&1
)
echo Launching Google Chrome at http://127.0.0.1:8080/ ...
start chrome http://127.0.0.1:8080/
echo Starting Yeast Promoter Modifier server...
python main.py
pause
